### ISSUE TITLE
Expose API in Lua to allow loading 'ppat' resources

### ISSUE THREAD

**Issue by tjhancocks** [EvocationGames/KestrelEngine#12]
_information required_

**Comment by warnwar** [comment]
@tjhancocks I saw this issue and thought I could probably make this happen, but I have a question for you. I noticed many of the other api assets inherit from image. Would this one inherit from it as well, or is it a special case?

**Comment by tjhancocks** [comment]
Yeah, it would inherit from the basic Image class. Though how the tiling would work needs to be thought about, as that should happen at the point of drawing (which is elsewhere).

For now getting it in a basic image is probably the best way forward.
