### ISSUE TITLE
Why duplicate Endless Sky?

### ISSUE THREAD

**Issue by BryanJBryce** [EvocationGames/KestrelEngine#41]
I'm wondering why there are two community projects Endless Sky and this one? https://github.com/endless-sky/

**Comment by tjhancocks** [comment]
Kestrel isn't meant to be Endless Sky. We have also answered this question a number of times.

Endless Sky takes a very different approach to making an EV Clone, and personally I just never got on with it. Kestrel is also not just being used for Cosmic Frontier. It will be used for other games. However what it provides to Cosmic Frontier is the ability to make use of the plugins from the original games, as uses the same resource file format as Nova did.
